version: 0.2	
  
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - pip install docker-compose
      - docker login -u $dockerhub_username -p $dockerhub_password
  build:
    commands:
      - docker build .
  post_build:
    commands:
      - echo Build completed on `date`