version: 0.1
  
phases:
  install:
    runtime-versions:
      nodejs: 13
  pre_build:
    commands:
      - pip install docker-compose
  build:
    commands:
      - docker build .
  post_build:
    commands:
      - echo Build completed on `date`